### ISSUE TITLE
カレンダーの今日の日付に色をつける

### ISSUE THREAD

**Issue by BcRikko** [BcRikko/XHISTORYS#6]
カレンダー表示時に、今日の日付に色をつける。

``` css
.calender-today {
    background-color: blue;
}
```

みたいな感じ
